=== Quinito/DAW/Practica_Grid/cristina turon/temperatura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="temperaturas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="provincia" type="xs:string"/>
        <xs:element name="fecha" type="xs:date"/>
                
        <xs:element name="tmpmin">
                  <xs:simpleType>
                  <xs:restriction base="xs:integer">
                          <xs:minInclusive value="-50"/>
                          <xs:maxInclusive value="50"/>
                  </xs:restriction>
                  </xs:simpleType>
         </xs:element>         
         
        <xs:element name="tmpmax">
                 <xs:simpleType>
                 <xs:restriction base="xs:integer">
                         <xs:minInclusive value="-50"/>
                         <xs:maxInclusive value="50"/>
                 </xs:restriction>
                </xs:simpleType>
        </xs:element>                  
  <!--
                 <xs:minInclusive value="-50"/>
                <xs:maxInclusive value="50"/>
        
       <xs:simpleType>
                   <xs:restriction base="xs:integer">
              <xs:minInclusive value="-50"/>
            </xs:restriction>
          </xs:simpleType> 
        
        </xs:element>
                
        <xs:element name="tmpmax" type="xs:integer" >
           <xs:minInclusive value="-50"/>
           <xs:maxInclusive value="50"/>
        </xs:element> -->
                
        <xs:element ref="incidencias"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="incidencias" >
    <xs:complexType>
      <xs:sequence>
       <xs:element name="nombre">   <!--<xs:element name="nombre" type="xs:integer">-->
        <xs:simpleType>
           <xs:restriction base="xs:string">
              <xs:enumeration value="frio"/>
              <xs:enumeration value="nieve"/>
              <xs:enumeration value="lluvia"/>
              <xs:enumeration value="calor"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      
           
         <xs:element name="severidad" >   <!--<xs:element name="severidad"  type="xs:integer">-->
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="alta"/>
              <xs:enumeration value="media"/>
              <xs:enumeration value="baja"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
        
<!--
      FÍJATE AQUÍ como no lleva el type que es lo que provoca la confusión al esquema al  volver a definir el tipo base como string; lo he copiado del w3schools
        
<xs:element name="car">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Audi"/>
      <xs:enumeration value="Golf"/>
      <xs:enumeration value="BMW"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>  -->

=== Quinito/DAW/Practica_Grid/cristina turon/temperatura.xml
<?xml version="1.0" encoding="UTF-8"?>
<temperaturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/media/madrid/MEMORIA%20USB/cristina%20turon/temperatura.xsd">
  <provincia>madrid</provincia>
  <fecha>2022-04-20</fecha>
  <tmpmin>3</tmpmin>
  <tmpmax>70</tmpmax>
  <incidencias>
    <nombre>frio</nombre>
    <severidad>alta</severidad>
  </incidencias>
</temperaturas>
